### ISSUE TITLE
Realizar a implementação json em C#

### ISSUE THREAD

**Issue by fabiolamfleury** [lab-neuro-comp/Scalemate#4]
Implementar nova lógica do Teste, Tester, Pergunta

**Comment by fabiolamfleury** [comment]
Usando a biblioteca [json.net](https://www.newtonsoft.com/json) é de simples uso para conversão de objetos para string json. É necessário apenas instalar a referência (pacote nuget) e utilizar das seguintes formas:

Para transformar um objeto em string json:
```
Product product = new Product();
product.Name = "Apple";
product.Expiry = new DateTime(2008, 12, 28);
product.Sizes = new string[] { "Small" };

string json = JsonConvert.SerializeObject(product);
// {
//   "Name": "Apple",
//   "Expiry": "2008-12-28T00:00:00",
//   "Sizes": [
//     "Small"
//   ]
// }
```

Recuperar o json:
```
string json = @"{
  'Name': 'Bad Boys',
  'ReleaseDate': '1995-4-7T00:00:00',
  'Genres': [
    'Action',
    'Comedy'
  ]
}";

Movie m = JsonConvert.DeserializeObject<Movie>(json);

string name = m.Name;
// Bad Boys
```

**Comment by gabrielalbino** [comment]
Fechando a issue pois já está pronto e receberá merge conjunto com a branch da nova arquitetura (WinForms)
